version: '3'

services:
  jenkins:
    container_name: jenkins-blueocean
    build: .
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - $HOME/projects:/projects
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
  dind:
    container_name: jenkins-docker
    image: docker:dind
    privileged: true
    restart: always
    tty: true
    networks:
      - jenkins
    ports:
      - 2376:2376
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_TLS_CERTDIR=/certs
  sonarqb:
    container_name: sonarqb
    image: sonarqube
    restart: always
    networks:
      - jenkins
      - sonar
    ports:
      - 9000:9000
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

networks:
  jenkins:
  sonar:

volumes:
  jenkins-data:
  jenkins-docker-certs:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-bundled-plugins:
    